name: chatty-duck-local

services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - chatty-duck-local-postgress:/var/lib/postgresql/data

volumes:
  chatty-duck-local-postgress:
    name: chatty-duck-local-postgress