name: Pull Request CI
run-name: Veryfing changes applied to backend with "${{ github.event.pull_request.title }}" PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        # cache: true # not enabled because of unconfigured package.lock.json files

    - name: testing
      run: ls -la

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release